---
output:
  pdf_document:
    latex_engine: xelatex
bibliography: "References/Supporting_AJT.bib"
csl: "References/jama.csl"
header-includes:
  - \usepackage{fontspec}
  - \usepackage{graphicx}
  - \usepackage{pdfpages}
  - \usepackage{fancyhdr}
  - \setmainfont{Arial}
  - \hyphenpenalty=10000
  - \exhyphenpenalty=10000
  - \pagestyle{fancy}
  - \fancyhf{}
  - \fancyfoot[R]{Page \thepage}
  - \renewcommand{\headrulewidth}{0pt}
  - \renewcommand{\footrulewidth}{0pt}
---

\begin{center}
\textit{\Large Supporting Information for:}
\end{center}

\begin{center}
\textbf{\Large Recipient Plasma Metabolomics as a Predictor of Heart Transplant Severe Primary Graft Dysfunction}
\end{center}

\vspace{1em}

Joshua D. Preston, BS^1,2^, Clayton J. Rust, MD^1^, Aubrey C. Reed, BS^1^, Supreet S. Randhawa, MS^1^, Ailin Tang, BS^1^, Kimberly A. Rooney, BS^3^, Misho Kozmava, BS^3^, Jaclyn Weinberg, BS^2^, Lucy Avant, BS^1^, Catherine L.B. McGeoch, MD, MSc^1^, Gustavo A. Parrilla, MD^1^, Jiada Zhan, BS, RD^2^, ViLinh Tran, MS^2^, Michael E. Halkos, MD, MSc^1^, Muath M. Bishawi, MD PhD^1^, Mani A. Daneshmand, MD^1^, Arshed A. Quyyumi, MD^3^, Charles D. Searles, MD^3^, Young-Mi Go, PhD^2^, Dean P. Jones, PhD^2^, Joshua L. Chan, MD^1^

\vspace{1em}

^1^Division of Cardiothoracic Surgery, Department of Surgery, Emory University School of Medicine, Atlanta, GA, USA

^2^Division of Pulmonary, Allergy, Critical Care, and Sleep Medicine, Department of Medicine, Emory University School of Medicine, Atlanta, GA, USA

^3^Division of Cardiology, Department of Medicine, Emory University School of Medicine, Atlanta, GA, USA

\vfill

# Table of Contents

\textbf{Supplemental Figure 1} \dotfill 2

\textbf{Supplemental Figure 2.1} \dotfill 3

\textbf{Supplemental Figure 2.2} \dotfill 4

\textbf{Supplemental Figure 2.3} \dotfill 5

\textbf{Supplemental Figure 2.4} \dotfill 6

\textbf{Supplemental Figure 2.5} \dotfill 7

\textbf{Expanded Metabolomics Methods and Other Technical Details} \dotfill 8-9

\quad \textit{Sample Collection and Processing} \dotfill 8

\quad \textit{Metabolomics Profiling with Liquid Chromatography-Mass Spectrometry} \dotfill 8

\quad \textit{Feature Extraction, Annotation, and Identification} \dotfill 8-9

\quad \textit{Quality Control and Data Transformation} \dotfill 9

\textbf{Statistical Analysis and Data Visualization} \dotfill 9-10

\quad \textit{Partial Least Squares Discriminant Analysis and Volcano Plots} \dotfill 9

\quad \textit{Pathway Enrichment Analysis} \dotfill 9-10

\quad \textit{Identified and Annotated Metabolite Analysis} \dotfill 10

\quad \textit{Sensitivity Analysis} \dotfill 10


\textbf{References} \dotfill 11-12

\newpage



\includepdf[pages=-,pagecommand={\noindent\textbf{\Large Supplemental Figure 1}\vspace{0.5cm}}]{Figures/PDF/S1.pdf}

\includepdf[pages=-,pagecommand={\noindent\textbf{\Large Supplemental Figure 2.1}\vspace{0.2cm}\\\noindent\textit{\fontsize{11}{13}\selectfont Markers on X-axis indicate Y/N severe PGD status.}\vspace{0.3cm}}]{Figures/PDF/S2.1.pdf}

\includepdf[pages=-,pagecommand={\noindent\textbf{\Large Supplemental Figure 2.2}\vspace{0.2cm}\\\noindent\textit{\fontsize{11}{13}\selectfont Markers on X-axis indicate Y/N severe PGD status.}\vspace{0.3cm}}]{Figures/PDF/S2.2.pdf}

\includepdf[pages=-,pagecommand={\noindent\textbf{\Large Supplemental Figure 2.3}\vspace{0.2cm}\\\noindent\textit{\fontsize{11}{13}\selectfont Markers on X-axis indicate Y/N severe PGD status.}\vspace{0.3cm}}]{Figures/PDF/S2.3.pdf}

\includepdf[pages=-,pagecommand={\noindent\textbf{\Large Supplemental Figure 2.4}\vspace{0.2cm}\\\noindent\textit{\fontsize{11}{13}\selectfont Markers on X-axis indicate Y/N severe PGD status.}\vspace{0.3cm}}]{Figures/PDF/S2.4.pdf}

\includepdf[pages=-,pagecommand={\noindent\textbf{\Large Supplemental Figure 2.5}\vspace{0.5cm}}]{Figures/PDF/S2.5.pdf}

# **Expanded Metabolomics Methods and Other Technical Details**
In keeping with consensus reporting standards for metabolomics experiments,[@sumnerProposedMinimumReporting2007] we provide in-depth metabolomics details as follows. In addition, we provide expanded details on statistical analyses and other technical details:

## *Sample Collection and Processing*
Blood samples were collected immediately before transplant into K2EDTA plasma preparation tubes. Once samples were collected from patients, they were immediately placed on ice. The samples remained on ice and were centrifuged at 2500 x g for 15 minutes at 4°C within 5 hours of collection (the mean time from collection to processing for all samples = 1 hour). Following centrifugation, three aliquots were made from the supernatant, which were stored at -80°C shortly after.

## *Metabolomics Profiling with Liquid Chromatography-Mass Spectrometry*
High-resolution metabolomics was performed in the Emory Clinical Biomarkers Laboratory as previously described.[@liuReferenceStandardizationQuantification2020] Plasma samples were thawed, and 10 μL of plasma was added to 190 μL of acetonitrile containing 2% internal standards. Samples were then vortexed and allowed to incubate on ice for 30 minutes. Following incubation, samples were centrifuged 20,817 x g for 10 minutes. Supernatants were then transferred into autosampler vials. These were loaded onto autosampler plates and were kept at -20°C until analysis. Pooled control plasma (Equitech-Bio, SHP45) and National Institute of Standards and Technology (NIST) reference plasma were prepared and analyzed in tandem.

\noindent\hspace{1.5em}Metabolomics analysis was conducted with a liquid chromatography-mass spectrometry system (LC-MS) consisting of a Vanquish Duo UHPLC coupled to an Orbitrap ID-X Tribrid Mass Spectrometer (Thermo Scientific). Autosampler plates containing samples were maintained at 4°C in the autosampler of the LC-MS throughout the analysis. Samples were analyzed in triplicate on a 5-minute method using C18 chromatography coupled to negative electrospray ionization (ESI) (C18-) and hydrophilic interaction liquid chromatography coupled to positive ESI (HILIC+). Analyte separation for HILIC was performed with a Waters Acquity BEH Amide HILIC column (2.1 mm x 100 mm, 1.7 μm particle size) and gradient elution with LCMS-grade solvents and additives. The HILIC mobile phases included (Buffer A) water with 1 mM ammonium acetate and 0.1\% formic acid and (Buffer B) 95\% acetonitrile with 1 mM ammonium acetate and 0.1\% formic acid. For the HILIC gradient, an initial 0.5 min hold at 90\% B was followed by a linear decrease to 20\% B from 0.6 to 2.55 min, a 2 min hold, and a 5-minute re-equilibration period. C18 chromatography was performed on a Thermo Hypersil Gold C18 column (2.1 mm x 100 mm, 1.9 μm particle size). The C18 mobile phases included (Buffer A) water with 1 mM ammonium acetate and (Buffer B) 99\% acetonitrile with 1 mM ammonium acetate. For the C18 gradient, an initial 0.5 min hold at 1\% B was followed by a 0.75 min linear increase to 99\% B, held for 3.75 min, and a 5-minute re-equilibration period. The flow rate for both methods was 0.3 mL/min, and the column compartment was heated to 45 °C. The mass spectrometer was operated at 120k resolution and MS1 scans were collected for m/z 85-1,275. Tune parameters consisted of sheath gas at 50, auxiliary gas at 10, and sweep gas at 1. The spray voltage was set to 3.50 kV for ESI+ and -2.75 kV for ESI-.

## *Feature Extraction, Annotation, and Identification*
ProteoWizard v3[@chambersCrossplatformToolkitMass2012] was used to convert raw spectral files to .mzXML files. Untargeted feature tables were then generated from extracted data using established laboratory workflows, softwares[@uppal2013; @jarrellPlasmaAcylcarnitineLevels2020; @yuApLCMSAdaptiveProcessing2009] (namely, apLCMS and xMSAnalyzer), and an in-house R package, \textit{MetaboJanitoR}, which is available upon request. All feature tables were corrected for batch effects using ComBat [@johnson2007] from the \textit{sva} package [@leek2012].

\noindent\hspace{1.5em}Untargeted feature tables comprised all HILIC+ and C18- features observed with a unique mass to charge ratio (m/z) and corresponding retention time (RT). Identified/annotated feature tables were made up Level 1[@schymanskiIdentifyingSmallMolecules2014] and Level 3[@schymanskiIdentifyingSmallMolecules2014] identifications. Level 1 identifications were obtained by ion dissociation mass spectrometry relative to authentic standards (mass error = ± 5 ppm, retention time threshold = ± 30 seconds). Level 3 identifications were made using an in-house annotation algorithm (see https://github.com/jamesjiadazhan for the future release of this R package upon its publication), which generates annotations based on precursor-product correlations (note: this version of the algorithm chose a single best adduct for the feature table based on the strength of the precursor-product correlation alone).
All raw data files (.mzXML format) and feature tables analyzed for this study will be available on October 31, 2026, through the NIH Common Fund's National Metabolomics Data Repository (NMDR) website, Metabolomics Workbench (Project ID PR002742; Study ID ST004328; Project DOI http://dx.doi.org/10.21228/M87549).

## *Quality Control and Data Transformation*
Features that were not detected in at least 80% of samples were excluded from analysis, but were included as background for pathway enrichment analysis. All '0' values (indicating non-detection by the instrument) were replaced with ½ the minimum value for that feature detected across all samples.[@weiMissingValueImputation2018] Following this, all intensity (peak area) values were log$_2$-transformed prior to further analysis. Features in identified/annotated feature tables that significantly differed between study groups (Severe PGD versus No Severe PGD) were manually inspected and evaluated for biological plausibility and annotation quality control. Only annotated features encompassing endogenous, microbiome-derived, or relevant pharmacological metabolites were included.

# **Statistical Analysis and Data Visualization**
The complete analytical pipeline and source code used for data processing and statistical analyses are publicly available at https://github.com/jdpreston30/PGD-preop-metabolomics. A containerized Docker image of the complete computational environment is available at Docker Hub (https://hub.docker.com/r/jdpreston30/pgd-preop-metabolomics), and the archived analysis pipeline is permanently available at Zenodo (DOI: [PLACEHOLDER - TO BE ASSIGNED UPON PUBLICATION]). 

\noindent\hspace{1.5em}Data were analyzed and visualized using Microsoft Excel (Mac v16.101.294, Microsoft Corporation, 2025), R (v4.5.1),[@rcoreteam2023] and MetaboAnalyst (v6.0)[@pangMetaboAnalyst60Unified2024] via the \textit{MetaboAnalystR} package.[@xia2025] All code was written, compiled, and run in Visual Studio Code (v1.104.2, Microsoft Corporation, 2025). All data visualizations were created using \textit{ggplot2},[@wickhamGgplot2ElegantGraphics2016] \textit{igraph},[@csardiIgraphSoftwarePackage2006; @antonovIgraphEnablesFast2023; @csardiIgraphNetworkAnalysis2025] and \textit{ggraph}.[@pedersenGgraphImplementationGrammar2025] All figures were compiled using \textit{cowplot}.[@clauso.wilke2025] Epidemiologic statistics were performed using the \textit{TernTablesR} package.[@preston2025] For all analyses, statistical significance was set at α = 0.05.

## *Partial Least Squares Discriminant Analysis and Volcano Plots*
Partial Least Squares Discriminant Analysis (PLS-DA) was performed using the R package mixOmics[@rohart2017]. Volcano plots were created by calculating p-values (based on Welch's t-tests on log$_2$-transformed data) to compare the means of each (untargeted) feature between groups, while fold changes were determined using untransformed data. All p-value calculations were performed using R's stats package. For purposes of visualization, p-values were then -log$_{10}$-transformed, and fold changes were log$_2$-transformed.

## *Pathway Enrichment Analysis*
All pathway enrichment analysis was performed using Mummichog[@li2013]. A full list of p-values comparing means of all features between groups was first generated in R using the stats package via Welch's t-tests. These features, including the m/z, retention time, and ESI mode, along with their corresponding p-values, were then analyzed using MetaboAnalyst's[@pangMetaboAnalyst60Unified2024] 'Functional Analysis' tool for LC-MS, which utilizes Mummichog[@li2013] as its core algorithm. Notably, this tool allows for the usage of Mummichog v2.0, which takes into account retention time and ESI mode, whereas the original algorithm simply used m/z. The parameters for the pathway enrichment included the following: mixed mode, 5 ppm mass tolerance, primary ions enforced, p-value cutoff = default for top 10% of peaks, KEGG and MFN \textit{homo sapiens} databases. A bubble plot was then constructed based on the p-values (Fisher’s) and enrichment factors generated by the algorithm output.

## *Identified and Annotated Metabolite Analysis*
For identified/annotated metabolites, Welch's t-tests were employed to determine the p-values comparing means between each group. FDR adjustments were performed using the Benjamini-Hochberg (BH) procedure. A representative set of various families of metabolites was selected and displayed in the main text figures (\textbf{Figure 3A-D}), but all significantly differing annotated or identified features are displayed in \textbf{Supplemental Figure 2}. Both raw p-values and FDR q-values are displayed on all plots displaying annotated/identified metabolites.

## *Sensitivity Analysis*
Given the exploratory and hypothesis-generating nature of the untargeted metabolomics study performed herein, which measured over 20,000 individual metabolic features, a conventional power analysis is not applicable. However, we conducted a quantitative post-hoc sensitivity analysis (further details of which can be found in the GitHub repository) to determine the minimum detectable effect size based on the group sizes in our study. With 62 patients (8 with severe PGD and 54 without), we had ~80\% power (α=0.05) to detect a minimum standardized mean difference of Cohen's d ≈ 1.08. Based on observed within-group variance (calculated using the filtered, i.e. post-QC, untargeted feature table), the median minimum detectable fold-change was 1.87 (IQR 1.46–2.99) across all features. Considering this, this study was powered to detect very large metabolic differences between groups, which is consistent with the exploratory and hypothesis-generating design. More subtle differences would require larger cohorts moving forward.

\newpage
# **References**
