#* 10: Validation Plots Organization
#+ 10.0: Notes
# The workflow was first to create the combined PDFs from 08. These were inspected visually and any obvious failures were assigned state = "failed" in the validation.xlsx file. Alternatively, any that clearly passed on first inspection were assigned "final".
# A quality score was given on the validation sheet- either F for fail, 1 for level 1, 2 for level 2. An asterisk on those indicates that there was an alternative ID for the same chemical which looked better (or state = "alternative").
# Level 1 quality was considered co-elution of 2 or more fragments of standard or sample within a reasonable time of each other. Far far spread in time was not considered a pass but close co-elution that could be reasonably explained by matrix effects was. Note that there were select cases where the quantiative fragment (asterisk, see below) could not be seen in the standard but could be seen in the sample, and the standard and sample had other co-eluting fragments. These were still considered level 1.
# Single fragments, even if co-eluting in standard and sample, were considered fails.
# Level 2 quality was when you could detect co-elution of 2 or more fragments in the sample but not the standard, or the standard co-eluting fragments were shifted extremely far away.
# The peak (asterisk) used for statistics/quant was considered closely in this process, such that if you zoomed in, even if it was a smaller peak in all of the co-eluting fragments, it still had to follow the same general trajectory as its other fragments. If it could really only be considered noise, then it was considered a fail.
#+ 10.1
validation_plot_metadata_ordered <- validation_plot_metadata %>%
  arrange(order) |>
  select(-c(IARC, VD))
#+ 10.2: Set vectors of figures
#- 10.1.1: Variant differences, level 1
VD1_plot_list <- validation_check_files |>
  arrange(order) |>
  filter(quality == 1, source %in% c("VD", "IARC and VD")) |>
  pull(plot)
#- 10.1.2: IARC, level 1
IARC1_plot_list <- validation_check_files |>
  arrange(order) |>
  filter(quality == 1, source %in% c("IARC", "IARC and VD")) |>
  pull(plot)
#- 10.1.1: Variant differences, level 1
VD2_plot_list <- validation_check_files |>
  arrange(order) |>
  filter(quality == 2, source %in% c("VD", "IARC and VD")) |>
  pull(plot)
#- 10.1.2: IARC, level 1
IARC2_plot_list <- validation_check_files |>
  arrange(order) |>
  filter(quality == 2, source %in% c("IARC", "IARC and VD")) |>
  pull(plot)
#+ 10.2: Load grobs for each set
#- 10.2.1: Variant differences, level 1
VD1_grobs <- purrr::map(VD1_plot_list, ~readRDS(file.path("Outputs/Validation/display", paste0(.x, ".rds"))))
#- 10.2.2: IARC, level 1
IARC1_grobs <- purrr::map(IARC1_plot_list, ~readRDS(file.path("Outputs/Validation/display", paste0(.x, ".rds"))))
#- 10.2.3: Variant differences, level 2
VD2_grobs <- purrr::map(VD2_plot_list, ~readRDS(file.path("Outputs/Validation/display", paste0(.x, ".rds"))))
#- 10.2.4: IARC, level 2
IARC2_grobs <- purrr::map(IARC2_plot_list, ~readRDS(file.path("Outputs/Validation/display", paste0(.x, ".rds"))))
#+ 10.3:
ok
> validation_plot_metadata_ordered
# A tibble: 54 × 6
   order quality id     short_name             sf plot               
   <dbl>   <dbl> <chr>  <chr>               <dbl> <chr>                         
 1     1       1 CP3017 o-Toluidine             2 Outputs/Validation/revised/gr…
 2     1       1 CP3017 o-Toluidine             2 Outputs/Validation/revised/gr…
 3     1       1 CP3017 o-Toluidine             3 Outputs/Validation/revised/gr…
 4     1       1 CP3017 o-Toluidine             3 Outputs/Validation/revised/gr…
 5     5       2 CP3007 MDA                     2 Outputs/Validation/revised/gr…
 6     7       1 CP2475 o-Tolidine              2 Outputs/Validation/final/grob…
 7     8       2 CP3001 o-aminoazotoluene       2 Outputs/Validation/final/grob…
 8    10       1 CP2220 Benz(a)anthracene       2 Outputs/Validation/final/grob…
 9    13       1 CP2225 Chrysene                2 Outputs/Validation/final/grob…
10    15       1 CP1090 Methoxychlor            2 Outputs/Validation/final/grob…
11    17       1 CP3068 Naphthalene             2 Outputs/Validation/final/grob…
12    19       1 CP3193 N-MeFOSAA               2 Outputs/Validation/revised/gr…
13    19       1 CP3193 N-MeFOSAA               2 Outputs/Validation/revised/gr…
14    20       1 CP3003 5-NOT                   2 Outputs/Validation/final/grob…
15    21       1 CP3025 Anthracene              2 Outputs/Validation/final/grob…
16    24       1 CP2227 Fluoranthene            2 Outputs/Validation/final/grob…
17    26       1 CP3078 Pyrene                  2 Outputs/Validation/final/grob…
18    27       1 CP2049 2,4'-Methoxychlor       2 Outputs/Validation/final/grob…
19    29       1 CP2506 3-Hydroxycarbofuran     2 Outputs/Validation/final/grob…
20    30       1 CP2516 Acetophenone            2 Outputs/Validation/final/grob…
21    33       2 CP3047 Dibutyl phthalate       2 Outputs/Validation/final/grob…
22    34       1 CP2043 Ethylan                 2 Outputs/Validation/final/grob…
23    35       1 CP3180 Hexanoic acid           2 Outputs/Validation/final/grob…
24    36       1 CP2145 Metalaxyl               2 Outputs/Validation/final/grob…
25    37       2 CP2252 Methylparaben           2 Outputs/Validation/final/grob…
26    38       2 CP3135 Napropamide             2 Outputs/Validation/final/grob…
27    39       2 CP2331 OD-PABA                 2 Outputs/Validation/final/grob…
28    42       1 CP3066 o-Cresol                2 Outputs/Validation/revised/gr…
29    42       1 CP3066 o-Cresol                2 Outputs/Validation/revised/gr…
30    43       1 CP2302 TTBNP                   2 Outputs/Validation/final/grob…
31    45       1 CP3153 Cyfluthrin              2 Outputs/Validation/final/grob…
32    47       1 CP2187 DNOP                    2 Outputs/Validation/final/grob…
33    48       1 CP2237 2,4-Dimethylphenol      2 Outputs/Validation/final/grob…
34    49       1 CP2382 MEHP                    2 Outputs/Validation/revised/gr…
35    49       1 CP2382 MEHP                    2 Outputs/Validation/revised/gr…
36    51       2 CP3148 Menthone                2 Outputs/Validation/revised/gr…
37    51       2 CP3148 Menthone                2 Outputs/Validation/revised/gr…
38    54       1 CP2490 Ethyl butyrate          2 Outputs/Validation/final/grob…
39    55       1 CP2133 Terbuthylazine          2 Outputs/Validation/final/grob…
40    56       1 CP3182 TEEP                    2 Outputs/Validation/revised/gr…
41    56       1 CP3182 TEEP                    2 Outputs/Validation/revised/gr…
42    58       1 CP2075 THPI                    2 Outputs/Validation/final/grob…
43    59       1 CP2365 Prosulfuron             2 Outputs/Validation/revised/gr…
44    59       1 CP2365 Prosulfuron             2 Outputs/Validation/revised/gr…
45    60       1 CP2370 DEET                    2 Outputs/Validation/final/grob…
46    62       2 CP3166 Flucythrinate           2 Outputs/Validation/final/grob…
47    64       1 CP1016 Pentachlorophenol       3 Outputs/Validation/final/grob…
48    65       1 CP1074 γ-BHC                   3 Outputs/Validation/final/grob…
49    71       2 CP2535 2-Naphthylamine         3 Outputs/Validation/final/grob…
50    72       1 CP2545 Phenacetin              3 Outputs/Validation/final/grob…
51    74       2 CP3002 4-ABP                   3 Outputs/Validation/final/grob…
52    75       2 CP3013 MOCA                    3 Outputs/Validation/final/grob…
53    77       2 CP3020 2-ABP                   3 Outputs/Validation/final/grob…
54    78       2 CP3028 Benzo[a]pyrene          3 Outputs/Validation/final/grob…


So as you can see i have externally put all the plots i want in my supplementary figures. I need you to add some stuff onto the pipeline that makes this tibble in 10.1. The order is arbitrary (i.e. the hard number doesnt mean anything) except the ORDER does (shows smallest to largest to display, ordinal) i know it skips numbers though.

So , i already set the supplementary figure number in "sf". 
First we will next we will make a sf_sub column which is just a paste of sf then quality with a period delimiter so either 2.1, 2.2, 3.1, or 3.2

I would like to add to this a sf_sub_order. this is always going to be a 1 or 2 . this determines if it is on the top half or bottom half of the page. there will always be two figures per page

For figures with two figures (i.e. has a plot that ends with _F) those will ALWAYS be 1 and 2. this is so that they alwaays end up on the same page if that makes sense. the _F will always be the 2 and the non _F the 1.

When there is a case of a figure with an _F, those end up on the same page as a _1 and _2 if that makes sense. however, if there is a sort of case wehre for example we are counting up, and it is an odd number, the ones with an _F should always be 2 which owld thus force its "parent" to always be a 1 (this prevents the parent from being printed on the bottom half of another page)


Make sense? 
