#* 20: Session and Environment Provenance
#! Writes SESSION_INFO.txt at the repo root so a reader can tie published results to an exact code state; .pipeline_start is set in run.R because this script runs last and cannot know when the pipeline began
#+ 20.1: Run Timing
.run_end <- Sys.time()
.run_start <- if (exists(".pipeline_start")) .pipeline_start else NULL
.fmt_time <- function(x) if (is.null(x)) "unknown" else format(x, "%Y-%m-%d %H:%M:%S %Z")
.elapsed <- if (is.null(.run_start)) "unknown (.pipeline_start not set in run.R)" else
  paste(format(round(as.numeric(difftime(.run_end, .run_start, units = "mins")), 2), nsmall = 2), "min")
#+ 20.2: Code Provenance
#! A commit SHA only means something alongside the clean/dirty state of the tree, so both are recorded; NULL distinguishes a failed git call from legitimately empty output
.git <- function(args) {
  out <- tryCatch(suppressWarnings(system2("git", args, stdout = TRUE, stderr = FALSE)), error = \(e) NULL)
  if (is.null(out) || !is.null(attr(out, "status"))) NULL else out
}
.sha <- .git(c("rev-parse", "HEAD"))
.branch <- .git(c("rev-parse", "--abbrev-ref", "HEAD"))
.dirty <- .git(c("status", "--porcelain"))
.tree_state <- if (is.null(.dirty)) "unknown (git unavailable)" else if (length(.dirty) == 0) "clean" else
  sprintf("DIRTY - %d uncommitted change(s); results may not correspond to the commit above", length(.dirty))
#+ 20.3: Assemble the Record
session_info_lines <- c(
  "Environmental Chemical Burden in Differentiated Thyroid Cancer",
  "Pipeline provenance record - generated by R/Scripts/19_session_info.R",
  strrep("=", 78),
  "",
  "RUN TIMING",
  paste("  started :", .fmt_time(.run_start)),
  paste("  finished:", .fmt_time(.run_end)),
  paste("  elapsed :", .elapsed),
  "",
  "CODE PROVENANCE (git)",
  paste("  commit      :", if (is.null(.sha)) "unavailable" else .sha[1]),
  paste("  branch      :", if (is.null(.branch)) "unavailable" else .branch[1]),
  paste("  working tree:", .tree_state),
  if (!is.null(.dirty) && length(.dirty) > 0) c("  uncommitted paths:", paste0("    ", .dirty)),
  "",
  "ENVIRONMENT",
  paste("  machine profile :", config$computer_used),
  paste("  config          :", "All_Run/config_dynamic.yaml"),
  paste("  package versions:", if (file.exists("renv.lock")) "pinned in renv.lock (authoritative)" else "renv.lock not found"),
  paste("  working dir     :", getwd()),
  "",
  "SESSION INFO",
  capture.output(sessionInfo()),
  "",
  strrep("=", 78)
)
#+ 20.4: Write to Repo Root
writeLines(session_info_lines, "SESSION_INFO.txt")
cat("Provenance written: SESSION_INFO.txt (", .tree_state, ")\n")
