#! INSTRUMENT ATTRIBUTION -- the GC1/GC2 labels in the archived OneDrive folder names are hand-applied and WRONG for the tumor batch. The instrument is identified by the acquisition host written at byte offset 98 of every .raw (HOSTNAME\account, plus its D: data root): GC2 = BJFCY23 with root Clinlc_Biomarkers_Laboratory_SSL; GC1 = THERMO-GC1 with root GC1_Clinic_Biomarkers_Lab_SSL. BOTH thyroid batches (GC080 tumor, GC097 cadaver) are BJFCY23, i.e. GC2 -- verified across 23 files spanning May 2022 to Aug 2024 and 15 studies, and the two hosts coexist in 2026 (GC115 batch on THERMO-GC1, GC116 batch on BJFCY23), which rules out a rename. The instrument never writes a GC1/GC2 token itself. 126 mzML still carry GC080_GC1_M524 in sourceFile@location; left as-is deliberately -- it is descriptive provenance that nothing resolves, and MS:INSTRUMENT_NAME in the mwTab is the authoritative field.
{
.pipeline_start <- Sys.time()
source("R/Utilities/Helpers/restore_renv.R")
source("R/Utilities/Helpers/load_dynamic_config.R")
config <- load_dynamic_config(computer = "auto", config_path = "All_Run/config_dynamic.yaml")
source("R/Scripts/00a_environment_setup.R")
source("R/Scripts/00b_setup.R")
source("R/Scripts/00c_FTs.R")
source("R/Scripts/00d_peakwalk_compile.R")
source("R/Scripts/01_clinical_data.R")
source("R/Scripts/02_detection.R")
source("R/Scripts/03_classes.R")
source("R/Scripts/04_variant_stats.R")
source("R/Scripts/05_variant_vis_prep.R")
source("R/Scripts/06_tumor_cadaver.R")
source("R/Scripts/07_validation_prep.R")
source("R/Scripts/08_validation_run.R")
source("R/Scripts/09_validation_plots_create.R")
source("R/Scripts/10_post_validation_clean.R")
source("R/Scripts/11_variant_vis.R")
source("R/Scripts/12_IARC_vis.R")
source("R/Scripts/13_confounding_analysis.R")
source("R/Scripts/14_render_figures.R")
source("R/Scripts/15_render_supplementary_figures.R")
source("R/Scripts/16_tables.R")
source("R/Scripts/17_supplementary_tables.R")
source("R/Scripts/18_construct_supplementary.R")
source("R/Scripts/19_session_info.R")
}
